/* ————————————————————————————————————————————————
   Static site data — no database required.
   Imagery: Unsplash, Pexels, and local studio renders.
———————————————————————————————————————————————— */

export type Plan = {
  id: number;
  slug: string;
  name: string;
  planNumber: string;
  price: number;
  bedrooms: number;
  bathrooms: number;
  livingSqFt: number;
  garageSqFt: number | null;
  porchSqFt: number | null;
  widthFt: number | null;
  depthFt: number | null;
  stories: string;
  style: string;
  badge: string | null;
  category: string;
  hasShop: boolean;
  hasRvGarage: boolean;
  featured: boolean;
  isNew: boolean;
  displayOrder: number;
  description: string;
  features: string[];
  heroImage: string;
  gallery: string[];
};

export type Post = {
  id: number;
  slug: string;
  title: string;
  excerpt: string;
  content: string[];
  category: string;
  author: string;
  image: string;
  readMinutes: number;
  publishedAt: Date;
};

export type Testimonial = {
  id: number;
  clientName: string;
  location: string;
  quote: string;
  project: string;
  displayOrder: number;
};

export type TeamMember = {
  id: number;
  name: string;
  role: string;
  bio: string;
  offClock: string;
  email: string;
  image: string;
  displayOrder: number;
};

/* Image helpers — all photography is served from the official
   Unsplash and Pexels CDNs. */
const U = (id: string) =>
  `https://images.unsplash.com/${id}?q=80&w=1600&auto=format&fit=crop`;
const PX = (id: string, ext = "jpeg") =>
  `https://images.pexels.com/photos/${id}/pexels-photo-${id}.${ext}?auto=compress&cs=tinysrgb&fit=crop&h=827&w=1400`;

import { POOL_LIFESTYLE } from "@/lib/media";

const FLOORPLAN = "/images/floorplan-main.jpg";
const GREAT_ROOM = "https://images.pexels.com/photos/7746642/pexels-photo-7746642.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=827&w=1400";

/* ——————————————————— PLANS ——————————————————— */

type PlanSeed = Omit<Plan, "id" | "porchSqFt" | "gallery"> & { extra?: string };

const SEEDS: PlanSeed[] = [
  {
    slug: "lances-place",
    name: "Lance's Place",
    planNumber: "#0027",
    price: 1850,
    bedrooms: 3,
    bathrooms: 2.5,
    livingSqFt: 2548,
    garageSqFt: 478,
    widthFt: 72,
    depthFt: 54,
    stories: "1",
    style: "Modern Barndominium",
    badge: "Featured",
    category: "Shop & Home",
    hasShop: true,
    hasRvGarage: false,
    featured: true,
    isNew: true,
    displayOrder: 1,
    description:
      "A hardworking shop house with a soft landing. Lance's Place pairs a wide-open great room and split bedrooms with a deep covered porch made for long evenings. The attached garage keeps daily life practical while the shop bay handles everything else.",
    features: [
      "Open-concept great room, kitchen and dining",
      "Split-bedroom layout with private primary suite",
      "Dedicated shop bay with oversized overhead door",
      "Deep covered front porch and rear patio",
      "Mudroom with drop zone and laundry",
      "Walk-in butler pantry",
    ],
    heroImage: "https://images.pexels.com/photos/37067773/pexels-photo-37067773.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=827&w=1400",
  },
  {
    slug: "the-modern-farmhouse",
    name: "The Modern Farmhouse",
    planNumber: "#0028",
    price: 1450,
    bedrooms: 3,
    bathrooms: 2,
    livingSqFt: 1792,
    garageSqFt: null,
    widthFt: 54,
    depthFt: 46,
    stories: "1",
    style: "Modern Farmhouse",
    badge: "Best Seller",
    category: "Family Living",
    hasShop: false,
    hasRvGarage: false,
    featured: true,
    isNew: true,
    displayOrder: 2,
    description:
      "Our most requested starter barndominium. Board-and-batten lines, a welcoming front porch and an efficient 3-bedroom layout that lives far larger than its footprint. Every square foot works hard.",
    features: [
      "Vaulted great room with fireplace",
      "Island kitchen open to dining",
      "Primary suite with walk-in closet",
      "Covered front porch and back patio",
      "Efficient single-story footprint",
      "Ready for detached shop pairing",
    ],
    heroImage: "https://images.unsplash.com/photo-1568605114967-8130f3a36994?q=80&w=1600&auto=format&fit=crop",
  },
  {
    slug: "pensacola-place",
    name: "Pensacola Place",
    planNumber: "#0025",
    price: 1300,
    bedrooms: 3,
    bathrooms: 2,
    livingSqFt: 1333,
    garageSqFt: 471,
    widthFt: 56,
    depthFt: 40,
    stories: "1",
    style: "Coastal Farmhouse",
    badge: "Under 1,500 SF",
    category: "Small Home",
    hasShop: false,
    hasRvGarage: false,
    featured: false,
    isNew: false,
    displayOrder: 3,
    description:
      "Compact, capable and full of light. Pensacola Place is a three-bedroom plan that keeps the budget honest without giving up a proper garage or a porch worth sitting on.",
    features: [
      "Efficient 3-bedroom split layout",
      "Attached 471 SF garage",
      "Covered entry porch",
      "Open kitchen to living room",
      "Oversized windows for natural light",
    ],
    heroImage: U("photo-1580587771525-78b9dba3b914"),
  },
  {
    slug: "family-lodge",
    name: "Family Lodge",
    planNumber: "#0026",
    price: 2450,
    bedrooms: 3,
    bathrooms: 2.5,
    livingSqFt: 4254,
    garageSqFt: 2835,
    widthFt: 118,
    depthFt: 62,
    stories: "1",
    style: "Rustic Lodge",
    badge: null,
    category: "Shop & Home",
    hasShop: true,
    hasRvGarage: true,
    featured: false,
    isNew: false,
    displayOrder: 4,
    description:
      "Half luxury lodge, half serious workspace. With over 2,800 SF of garage and shop under the same roof as 4,254 SF of living, the Family Lodge is built for people whose hobbies need their own zip code.",
    features: [
      "Timber-framed great room with window wall",
      "2,835 SF garage and shop wing — RV ready",
      "Luxury primary suite with spa bath",
      "Multiple covered outdoor living areas",
      "Mudroom, safe room and walk-in pantry",
    ],
    heroImage: "https://images.pexels.com/photos/36777966/pexels-photo-36777966.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=827&w=1400",
  },
  {
    slug: "palm-cottage",
    name: "Palm Cottage",
    planNumber: "#0023",
    price: 2250,
    bedrooms: 4,
    bathrooms: 4.5,
    livingSqFt: 3504,
    garageSqFt: 1091,
    widthFt: 84,
    depthFt: 58,
    stories: "1",
    style: "Coastal Retreat",
    badge: null,
    category: "Estate",
    hasShop: false,
    hasRvGarage: false,
    featured: false,
    isNew: false,
    displayOrder: 5,
    description:
      "Every bedroom gets its own bath in this resort-minded four-bedroom plan. Palm Cottage wraps indoor-outdoor living around a breezy great room built for gathering.",
    features: [
      "Four ensuite bedrooms",
      "1,091 SF garage",
      "Indoor-outdoor great room",
      "Covered lanai and outdoor kitchen pad",
      "Dedicated study / flex room",
    ],
    heroImage: PX("24017315"),
  },
  {
    slug: "the-lakehouse",
    name: "The Lakehouse",
    planNumber: "#0024",
    price: 2250,
    bedrooms: 5,
    bathrooms: 3.5,
    livingSqFt: 3793,
    garageSqFt: 697,
    widthFt: 78,
    depthFt: 62,
    stories: "1.5",
    style: "Lakefront",
    badge: "Featured",
    category: "Retreat",
    hasShop: false,
    hasRvGarage: false,
    featured: true,
    isNew: false,
    displayOrder: 6,
    description:
      "Designed around the view. The Lakehouse stacks five bedrooms, a window-walled great room and a wraparound deck into a retreat that sleeps the whole crew in comfort.",
    features: [
      "Five bedrooms — sleeps a crowd",
      "Wall of glass facing the water",
      "Wraparound deck with outdoor fireplace",
      "Bunk-friendly upper loft",
      "697 SF garage for lake toys",
    ],
    heroImage: "https://images.unsplash.com/photo-1470770841072-f978cf4d019e?q=80&w=1600&auto=format&fit=crop",
  },
  {
    slug: "the-ivy-home",
    name: "The Ivy Home",
    planNumber: "#0021",
    price: 2250,
    bedrooms: 4,
    bathrooms: 2.5,
    livingSqFt: 3430,
    garageSqFt: 2203,
    widthFt: 96,
    depthFt: 58,
    stories: "1",
    style: "Traditional Barndominium",
    badge: null,
    category: "Shop & Home",
    hasShop: true,
    hasRvGarage: true,
    featured: false,
    isNew: false,
    displayOrder: 7,
    description:
      "A stately four-bedroom home with a 2,203 SF shop that swallows RVs, boats and project cars whole. The Ivy Home is equal parts elegance and payload.",
    features: [
      "2,203 SF garage and shop — RV ready",
      "Four bedrooms with walk-in closets",
      "Formal entry and study",
      "Covered rear patio with fireplace",
      "Game room / second living area",
    ],
    heroImage: PX("36777966"),
  },
  {
    slug: "honeysuckle-cottage",
    name: "Honeysuckle Cottage",
    planNumber: "#0022",
    price: 2250,
    bedrooms: 4,
    bathrooms: 4,
    livingSqFt: 3593,
    garageSqFt: 1023,
    widthFt: 86,
    depthFt: 60,
    stories: "1",
    style: "Cottage",
    badge: null,
    category: "Family Living",
    hasShop: false,
    hasRvGarage: false,
    featured: false,
    isNew: false,
    displayOrder: 8,
    description:
      "Southern-hospitality square footage: four bedrooms, four baths, a wraparound porch and a kitchen that keeps the cook in the conversation.",
    features: [
      "Four bedrooms, two full and two half baths",
      "Wraparound covered porch",
      "1,023 SF garage",
      "Butler pantry and prep kitchen",
      "Keeping room off the main living",
    ],
    heroImage: U("photo-1568605114967-8130f3a36994"),
  },
  {
    slug: "the-sedona",
    name: "The Sedona",
    planNumber: "#0019",
    price: 1850,
    bedrooms: 4,
    bathrooms: 2.5,
    livingSqFt: 2650,
    garageSqFt: 485,
    widthFt: 68,
    depthFt: 48,
    stories: "1",
    style: "Modern Barndominium",
    badge: null,
    category: "Modern",
    hasShop: false,
    hasRvGarage: false,
    featured: false,
    isNew: false,
    displayOrder: 9,
    description:
      "Clean rooflines and a gallery-like great room give The Sedona a modern edge, while four bedrooms keep it grounded in family life.",
    features: [
      "Modern shed-and-gable roof composition",
      "Four bedrooms plus flex space",
      "Window-walled great room",
      "485 SF garage",
      "Covered patio for outdoor dining",
    ],
    heroImage: "https://images.pexels.com/photos/8134820/pexels-photo-8134820.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=827&w=1400",
  },
  {
    slug: "rachels-place",
    name: "Rachel's Place",
    planNumber: "#0020",
    price: 1850,
    bedrooms: 3,
    bathrooms: 2,
    livingSqFt: 2833,
    garageSqFt: 1165,
    widthFt: 92,
    depthFt: 52,
    stories: "1",
    style: "Farmhouse Barndominium",
    badge: null,
    category: "Shop & Home",
    hasShop: true,
    hasRvGarage: false,
    featured: false,
    isNew: false,
    displayOrder: 10,
    description:
      "A gracious three-bedroom ranch-style barndo with an 1,165 SF garage and workshop — room to spread out, inside and out.",
    features: [
      "1,165 SF garage and workshop",
      "Split-bedroom ranch layout",
      "Large island kitchen",
      "Fireplace in great room",
      "Covered back porch",
    ],
    heroImage: PX("36777847"),
  },
  {
    slug: "the-stallion",
    name: "The Stallion",
    planNumber: "#0017",
    price: 1650,
    bedrooms: 2,
    bathrooms: 2,
    livingSqFt: 2240,
    garageSqFt: 1120,
    widthFt: 80,
    depthFt: 48,
    stories: "1.5",
    style: "Equestrian Barndominium",
    badge: null,
    category: "Shop & Home",
    hasShop: true,
    hasRvGarage: false,
    featured: false,
    isNew: false,
    displayOrder: 11,
    description:
      "Built for horse people: two bedrooms, a 1,120 SF garage-plus-tack wing and 657 SF of second-floor flex space above it all.",
    features: [
      "1,120 SF garage with tack / storage room",
      "657 SF second-floor loft",
      "Two ensuite bedrooms",
      "Mudroom with wash station",
      "Porch views toward the paddock",
    ],
    heroImage: U("photo-1512917774080-9991f1c4c750"),
  },
  {
    slug: "the-breton",
    name: "The Breton",
    planNumber: "#0018",
    price: 1850,
    bedrooms: 4,
    bathrooms: 3.5,
    livingSqFt: 2833,
    garageSqFt: 1165,
    widthFt: 92,
    depthFt: 52,
    stories: "1",
    style: "European Cottage",
    badge: null,
    category: "Family Living",
    hasShop: false,
    hasRvGarage: false,
    featured: false,
    isNew: false,
    displayOrder: 12,
    description:
      "Brick warmth and barn proportions. The Breton's four bedrooms and 1,165 SF shop are wrapped in old-world curb appeal.",
    features: [
      "Four bedrooms, 3.5 baths",
      "1,165 SF garage and shop",
      "Brick and board-and-batten exterior",
      "Formal dining and study",
      "Outdoor fireplace patio",
    ],
    heroImage: PX("7587470"),
  },
  {
    slug: "the-springfield",
    name: "The Springfield",
    planNumber: "#0015",
    price: 2650,
    bedrooms: 2,
    bathrooms: 3.5,
    livingSqFt: 5583,
    garageSqFt: 2107,
    widthFt: 124,
    depthFt: 66,
    stories: "2",
    style: "Grand Barndominium",
    badge: "Largest Plan",
    category: "Estate",
    hasShop: true,
    hasRvGarage: false,
    featured: false,
    isNew: false,
    displayOrder: 13,
    description:
      "Our flagship. Nearly 5,600 SF of living on two levels with a 2,107 SF garage — a barndominium for entertaining on a grand scale.",
    features: [
      "Two-story grand living hall",
      "2,107 SF garage and shop",
      "Dual primary-worthy suites",
      "Game room, theater and wet bar",
      "Porte-cochère arrival court",
    ],
    heroImage: PX("8092387"),
  },
  {
    slug: "chester-place",
    name: "Chester Place",
    planNumber: "#0016",
    price: 1450,
    bedrooms: 3,
    bathrooms: 2,
    livingSqFt: 1894,
    garageSqFt: 1498,
    widthFt: 88,
    depthFt: 46,
    stories: "1",
    style: "Farmhouse Barndominium",
    badge: null,
    category: "Shop & Home",
    hasShop: true,
    hasRvGarage: false,
    featured: false,
    isNew: false,
    displayOrder: 14,
    description:
      "The classic barndo equation: a tidy three-bedroom home joined to a genuinely useful 1,498 SF shop. Chester Place punches above its price.",
    features: [
      "1,498 SF garage and shop",
      "Efficient three-bedroom layout",
      "Vaulted main living space",
      "Mudroom connection to shop",
      "Covered front porch",
    ],
    heroImage: PX("14399476"),
  },
  {
    slug: "the-evergreen",
    name: "The Evergreen",
    planNumber: "#0013",
    price: 1850,
    bedrooms: 3,
    bathrooms: 2,
    livingSqFt: 2590,
    garageSqFt: 1410,
    widthFt: 94,
    depthFt: 50,
    stories: "1",
    style: "Modern Farmhouse",
    badge: null,
    category: "Shop & Home",
    hasShop: true,
    hasRvGarage: false,
    featured: false,
    isNew: false,
    displayOrder: 15,
    description:
      "Balanced and bright. The Evergreen divides its square footage evenly between a calm three-bedroom home and a 1,410 SF dream garage.",
    features: [
      "1,410 SF garage and shop",
      "Light-filled open living",
      "Walk-through pantry",
      "Home office nook",
      "Covered patio with grill station",
    ],
    heroImage: PX("37650049"),
  },
  {
    slug: "jacobs-family-home",
    name: "Jacobs Family Home",
    planNumber: "#0014",
    price: 1650,
    bedrooms: 3,
    bathrooms: 3.5,
    livingSqFt: 2400,
    garageSqFt: 900,
    widthFt: 72,
    depthFt: 56,
    stories: "1",
    style: "Ranch Barndominium",
    badge: null,
    category: "Multigenerational",
    hasShop: false,
    hasRvGarage: false,
    featured: false,
    isNew: false,
    displayOrder: 16,
    description:
      "Family compound energy: a three-bedroom main home, 900 SF garage and a matching 900 SF guest house for the people who stay a while.",
    features: [
      "Detached 900 SF guest house included",
      "900 SF garage",
      "Three ensuite-style bedrooms",
      "Courtyard between structures",
      "Covered breezeways",
    ],
    heroImage: PX("17645479"),
  },
  {
    slug: "magnolia-ranch",
    name: "Magnolia Ranch",
    planNumber: "#0011",
    price: 2250,
    bedrooms: 4,
    bathrooms: 4.5,
    livingSqFt: 3700,
    garageSqFt: null,
    widthFt: 82,
    depthFt: 58,
    stories: "1",
    style: "Southern Ranch",
    badge: null,
    category: "Estate",
    hasShop: false,
    hasRvGarage: false,
    featured: false,
    isNew: false,
    displayOrder: 17,
    description:
      "A wide-shouldered southern ranch barndo with four bedrooms, four-and-a-half baths and porch space measured in honest-to-goodness yards.",
    features: [
      "Four bedrooms, 4.5 baths",
      "Deep wraparound porch",
      "Chef kitchen with double islands",
      "Primary suite with sitting room",
      "Detached shop-ready site plan",
    ],
    heroImage: PX("8134821"),
  },
  {
    slug: "mother-daughter-estate",
    name: "Mother-Daughter Estate",
    planNumber: "#0012",
    price: 1650,
    bedrooms: 3,
    bathrooms: 3,
    livingSqFt: 2496,
    garageSqFt: 850,
    widthFt: 70,
    depthFt: 54,
    stories: "1",
    style: "Multigenerational",
    badge: null,
    category: "Multigenerational",
    hasShop: false,
    hasRvGarage: false,
    featured: false,
    isNew: false,
    displayOrder: 18,
    description:
      "Two complete living quarters under one roofline — a respectful, well-designed answer to multigenerational living.",
    features: [
      "Dual primary living quarters",
      "Two full kitchens",
      "Shared 850 SF garage",
      "Private entrances and porches",
      "Connected yet independent layouts",
    ],
    heroImage: U("photo-1523217582562-09d0def993a6"),
  },
  {
    slug: "the-woody",
    name: "The Woody",
    planNumber: "#0009",
    price: 1300,
    bedrooms: 2,
    bathrooms: 1,
    livingSqFt: 1750,
    garageSqFt: null,
    widthFt: 48,
    depthFt: 40,
    stories: "1",
    style: "Cabin Barndominium",
    badge: null,
    category: "Small Home",
    hasShop: false,
    hasRvGarage: false,
    featured: false,
    isNew: false,
    displayOrder: 19,
    description:
      "A woodsy two-bedroom hideaway that proves good design doesn't need big numbers. Simple, warm, and easy to build.",
    features: [
      "Two-bedroom cabin layout",
      "Cathedral-ceiling living room",
      "Loft-ready upper volume",
      "Deep front porch",
      "Simple rectangular footprint",
    ],
    heroImage: PX("3865399"),
  },
  {
    slug: "the-jones-place",
    name: "The Jones Place",
    planNumber: "#0010",
    price: 1650,
    bedrooms: 3,
    bathrooms: 3,
    livingSqFt: 2100,
    garageSqFt: 2000,
    widthFt: 98,
    depthFt: 48,
    stories: "1",
    style: "Shop House",
    badge: null,
    category: "Shop & Home",
    hasShop: true,
    hasRvGarage: true,
    featured: false,
    isNew: false,
    displayOrder: 20,
    description:
      "For those who measure their dreams in bay doors: a comfortable three-bedroom paired with a full 2,000 SF shop.",
    features: [
      "2,000 SF shop — RV capable",
      "Three bedrooms, three baths",
      "Interior shop-to-mudroom entry",
      "Covered patio off great room",
      "Storage loft over shop",
    ],
    heroImage: PX("37067773"),
  },
  {
    slug: "the-sundowner",
    name: "The Sundowner",
    planNumber: "#0007",
    price: 1450,
    bedrooms: 2,
    bathrooms: 2,
    livingSqFt: 1610,
    garageSqFt: 2230,
    widthFt: 96,
    depthFt: 44,
    stories: "1",
    style: "RV Barndominium",
    badge: "RV Ready",
    category: "RV Garage",
    hasShop: true,
    hasRvGarage: true,
    featured: false,
    isNew: false,
    displayOrder: 21,
    description:
      "The traveler's home base. Live in a crisp two-bedroom apartment attached to a 2,230 SF garage with a true RV-height bay.",
    features: [
      "2,230 SF garage with 14' RV bay",
      "Efficient two-bedroom residence",
      "Full hookups planned at bay",
      "Covered porch for sunset watch",
      "Expandable second-story option",
    ],
    heroImage: PX("8134820"),
  },
  {
    slug: "the-todd",
    name: "The Todd",
    planNumber: "#0008",
    price: 2050,
    bedrooms: 5,
    bathrooms: 4,
    livingSqFt: 3158,
    garageSqFt: null,
    widthFt: 76,
    depthFt: 52,
    stories: "2",
    style: "Family Barndominium",
    badge: null,
    category: "Family Living",
    hasShop: false,
    hasRvGarage: false,
    featured: false,
    isNew: false,
    displayOrder: 22,
    description:
      "Five bedrooms, four baths, zero squabbles. The Todd is the big-family barndo with a place for everyone and everything.",
    features: [
      "Five bedrooms, four full baths",
      "Upstairs game room",
      "Jack-and-jill secondary suites",
      "Large laundry and mudroom",
      "Wraparound porch",
    ],
    heroImage: U("photo-1600596542815-ffad4c1539a9"),
  },
  {
    slug: "the-oasis",
    name: "The Oasis",
    planNumber: "#0005",
    price: 2050,
    bedrooms: 2,
    bathrooms: 2,
    livingSqFt: 3049,
    garageSqFt: 1296,
    widthFt: 96,
    depthFt: 54,
    stories: "1",
    style: "Resort Barndominium",
    badge: null,
    category: "Retreat",
    hasShop: false,
    hasRvGarage: false,
    featured: false,
    isNew: false,
    displayOrder: 23,
    description:
      "Two bedrooms, endless living space. The Oasis trades bedroom count for a resort-scale great room and 1,296 SF of garage.",
    features: [
      "Resort-scale open living",
      "1,296 SF garage",
      "Spa-style primary bath",
      "Outdoor kitchen pad",
      "Courtyard entry",
    ],
    heroImage: PX("5997994"),
  },
  {
    slug: "clydesdale-cottage",
    name: "Clydesdale Cottage",
    planNumber: "#0006",
    price: 1450,
    bedrooms: 3,
    bathrooms: 2,
    livingSqFt: 1984,
    garageSqFt: null,
    widthFt: 52,
    depthFt: 44,
    stories: "1",
    style: "Cottage",
    badge: null,
    category: "Small Home",
    hasShop: false,
    hasRvGarage: false,
    featured: false,
    isNew: false,
    displayOrder: 24,
    description:
      "Sturdy and charming in equal measure, Clydesdale Cottage is a three-bedroom cottage barndo that's easy on the eye and the budget.",
    features: [
      "Storybook cottage exterior",
      "Three bedrooms, two baths",
      "Garden-wall kitchen",
      "Covered porch and patio",
      "Simple, efficient footprint",
    ],
    heroImage: "https://images.pexels.com/photos/3865399/pexels-photo-3865399.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=827&w=1400",
  },
  {
    slug: "pine-cottage",
    name: "Pine Cottage",
    planNumber: "#0003",
    price: 1300,
    bedrooms: 2,
    bathrooms: 2,
    livingSqFt: 1500,
    garageSqFt: null,
    widthFt: 44,
    depthFt: 38,
    stories: "1",
    style: "Cottage",
    badge: null,
    category: "Small Home",
    hasShop: false,
    hasRvGarage: false,
    featured: false,
    isNew: false,
    displayOrder: 25,
    description:
      "A right-sized two-bedroom cottage barndo for first builds, lake lots and guest quarters — small in footprint, big on intention.",
    features: [
      "Two bedrooms, two full baths",
      "Vaulted main room",
      "Efficient galley-plus kitchen",
      "Front and rear porches",
      "Economical rectangular build",
    ],
    heroImage: U("photo-1470770841072-f978cf4d019e"),
  },
  {
    slug: "prairie-homestead",
    name: "Prairie Homestead",
    planNumber: "#0004",
    price: 1850,
    bedrooms: 4,
    bathrooms: 4,
    livingSqFt: 2539,
    garageSqFt: 715,
    widthFt: 74,
    depthFt: 50,
    stories: "1",
    style: "Prairie Farmhouse",
    badge: null,
    category: "Family Living",
    hasShop: false,
    hasRvGarage: false,
    featured: false,
    isNew: false,
    displayOrder: 26,
    description:
      "Wide-front-porch prairie living with four bedrooms and four baths sized for an honest family homestead.",
    features: [
      "Four bedrooms, four baths",
      "715 SF garage",
      "Homestead kitchen with hearth",
      "Mudroom and boot bench",
      "Full-width front porch",
    ],
    heroImage: PX("9748778"),
  },
  {
    slug: "danis-place",
    name: "Dani's Place",
    planNumber: "#0001",
    price: 1300,
    bedrooms: 2,
    bathrooms: 2,
    livingSqFt: 1167,
    garageSqFt: null,
    widthFt: 40,
    depthFt: 32,
    stories: "1",
    style: "Cottage",
    badge: "Starter Favorite",
    category: "Small Home",
    hasShop: false,
    hasRvGarage: false,
    featured: false,
    isNew: false,
    displayOrder: 27,
    description:
      "The plan that started it all. Dani's Place is our most attainable barndo — two bedrooms, two baths, and every dollar accounted for.",
    features: [
      "Most affordable plan in the library",
      "Two bedrooms, two baths",
      "Open-concept main room",
      "Covered entry porch",
      "Ideal guest house or first home",
    ],
    heroImage: PX("27988213", "png"),
  },
  {
    slug: "the-redwood",
    name: "The Redwood",
    planNumber: "#0002",
    price: 1650,
    bedrooms: 4,
    bathrooms: 4,
    livingSqFt: 2350,
    garageSqFt: 710,
    widthFt: 72,
    depthFt: 46,
    stories: "1",
    style: "Timber Barndominium",
    badge: null,
    category: "Family Living",
    hasShop: false,
    hasRvGarage: false,
    featured: false,
    isNew: false,
    displayOrder: 28,
    description:
      "Heavy timber character with a family-ready four-bedroom plan and a 710 SF garage for the trail rigs.",
    features: [
      "Four bedrooms, four baths",
      "710 SF garage",
      "Exposed timber detailing",
      "Stone fireplace",
      "Covered outdoor living",
    ],
    heroImage: U("photo-1518780664697-55e3ad937233"),
  },
  {
    slug: "high-sierra",
    name: "High Sierra",
    planNumber: "#0029",
    price: 2450,
    bedrooms: 3,
    bathrooms: 2,
    livingSqFt: 4270,
    garageSqFt: null,
    widthFt: 88,
    depthFt: 56,
    stories: "1.5",
    style: "Mountain Modern",
    badge: "New",
    category: "Retreat",
    hasShop: false,
    hasRvGarage: false,
    featured: false,
    isNew: true,
    displayOrder: 29,
    description:
      "Our newest release. High Sierra stretches 4,270 SF around a glass-and-timber great room built to frame a view worth the drive.",
    features: [
      "Newest plan in the library",
      "Glass-walled great room",
      "Three suites + bunk loft",
      "Expansive view-facing deck",
      "Ski-lodge mudroom",
    ],
    heroImage: PX("4933643"),
  },
];

/* Every plan carries a rich 6-image gallery: hero, lifestyle details,
   the floor plan sheet, and interior/jobsite shots from the media pool. */
export const PLANS: Plan[] = SEEDS.map((p, i) => {
  const rot = (n: number) => POOL_LIFESTYLE[(n + i * 3) % POOL_LIFESTYLE.length];
  return {
    ...p,
    id: i + 1,
    porchSqFt: null,
    gallery: [
      p.heroImage,
      i % 2 === 0 ? GREAT_ROOM : rot(1),
      FLOORPLAN,
      rot(2),
      rot(3),
      rot(4),
      ...(p.extra ? [p.extra] : []),
    ],
  };
});

/* ——————————————————— POSTS ——————————————————— */

export const POSTS: Post[] = [
  {
    id: 1,
    slug: "embracing-outdoor-lifestyle",
    title:
      "Embracing the Outdoor Lifestyle: Why Barndominiums Are the Perfect Fit",
    excerpt:
      "People are increasingly drawn to the idea of spending more time outside. Here's why the barndominium may be the perfect architecture for that shift.",
    category: "Lifestyle",
    author: "Greg James",
    image: "https://images.unsplash.com/photo-1470770841072-f978cf4d019e?q=80&w=1600&auto=format&fit=crop",
    readMinutes: 4,
    publishedAt: new Date("2024-12-12"),
    content: [
      "In recent years, there has been a significant shift toward outdoor living. People are increasingly drawn to the idea of spending more time on their porches, around fire pits, and under big skies — and the homes we design are changing to match.",
      "A barndominium is unusually well suited to this way of life. Because the roof is carried by the exterior walls, the interior can open completely to covered porches and patios with oversized doors. The line between inside and outside gets wonderfully blurry.",
      "## Design moves that bring the outside in",
      "The best outdoor-connected barndos share a few traits. A deep covered porch on the view side. A great room with a full height window wall or sliding glass panels. A mudroom where boots and dogs are welcome. Durable finishes — sealed concrete, wood, and metal — that don't mind a little weather.",
      "## The land is the amenity",
      "Most of our clients are building on acreage for the first time. The advice we give every one of them: spend time on the property before we draw. Watch where the sun sets, where the wind comes from, where the water moves. Then we'll put the porch in exactly the right place.",
      "When you're ready, browse our collection of stock plans — every one of them can be customized for your land, your views, and the way you actually live.",
    ],
  },
  {
    id: 2,
    slug: "benefits-and-challenges",
    title: "The Benefits and Challenges of Barndominium Living",
    excerpt:
      "Thinking of building a barndominium? An honest look at the pros and cons of this unique living style before you commit.",
    category: "Buying Guide",
    author: "Greg James",
    image: "https://images.pexels.com/photos/37067773/pexels-photo-37067773.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=827&w=1400",
    readMinutes: 5,
    publishedAt: new Date("2024-11-19"),
    content: [
      "We love barndominiums — we've designed hundreds of them. But part of our job is telling you when one may not be the right fit. Here's the honest breakdown we give every new client.",
      "## Why a barndo may be right for your family",
      "Large, wide-open spaces. Because a steel building or wood post-frame building carries its roof on the exterior walls only, the interior is left for unlimited design possibilities. Great rooms, shop connections, and flexible layouts are all on the table.",
      "Architectural flexibility. From farmhouse to modern and anything in between, these structures take on your style rather than forcing one on you. The simple envelope is a canvas.",
      "Cost efficiency. A simple rectangle with a metal skin is one of the most cost-effective ways to enclose space — especially with a post-frame building, which needs no traditional perimeter foundation.",
      "## When it may not be the best choice",
      "Design geometry. If your vision moves outside of a rectangle, costs climb quickly. This is where wood post-frame has an edge over steel — wood structures handle roof hips and changes of direction much more gracefully.",
      "HOA restrictions. Many HOAs will not allow metal-clad structures. There are workarounds — like brick or stone veneer walls with a metal roof left exposed — but check your covenants before you fall in love with a design.",
      "Still not sure? A short consultation can save months of second-guessing. Bring us your land, your wish list, and your questions.",
    ],
  },
  {
    id: 3,
    slug: "steel-vs-post-frame",
    title: "Steel vs. Post-Frame: Choosing the Right Building System",
    excerpt:
      "Weld-up, bolt-up, or wood post-frame? Here's how the three main barndominium building systems compare on cost, look, and buildability.",
    category: "Construction Systems",
    author: "Lance — Greg James Designs",
    image: "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?q=80&w=2000&auto=format&fit=crop",
    readMinutes: 6,
    publishedAt: new Date("2025-02-04"),
    content: [
      "Every barndominium starts with the same big decision: what holds the roof up? The three systems we design around most are steel weld-up, steel bolt-up, and wood post-frame. None is universally best — each wins somewhere.",
      "## Wood post-frame",
      "Often 15–20% less expensive than steel depending on size and location. No traditional foundation required, which can save thousands. Easy to erect — a real option for a capable DIY client. Wood handles roof hips and direction changes better than steel, so it suits more complex footprints. The trade-offs: eave heights usually capped around 18 feet, spans around 60 feet, a lower fire rating, and termites are a consideration as with any wood structure.",
      "## Steel weld-up",
      "A rigid frame shop-welded on site. Excellent for wide clear spans, tall walls, and big door openings — the RV bay crowd. Fire resistant and termite-proof. Costs more than post-frame and changes of direction in the roof get expensive fast.",
      "## Steel bolt-up (red iron)",
      "Pre-engineered frames arrive and bolt together. Predictable engineering and pricing at larger sizes, fast erection, and long clear spans. Least flexible once it's ordered — the drawings are the building.",
      "## Our rule of thumb",
      "Shops, equipment, RVs and tall doors: look at steel. Homes with complex rooflines, porches and hips: post-frame often pencils out better. And remember — every plan in our library can be adapted to any of the three systems.",
    ],
  },
  {
    id: 4,
    slug: "cost-to-build-barndominium",
    title: "How Much Does It Cost to Build a Barndominium in 2026?",
    excerpt:
      "Budget honestly. A breakdown of shell, finish-out, site work and the line items first-time builders most often forget.",
    category: "Budget & Cost",
    author: "Greg James",
    image: GREAT_ROOM,
    readMinutes: 7,
    publishedAt: new Date("2026-01-20"),
    content: [
      "It's the first question everyone asks, and the honest answer is: it depends on the variables you control. But you can budget with confidence once you understand where the money goes.",
      "## The four buckets",
      "One: the shell. Materials and erection of the building itself — post-frame shells are currently the most economical per square foot. Two: the interior finish-out, which ranges from simple and durable to genuinely luxurious. This is where budgets are made or broken. Three: site work — drive, well, septic, utilities — the hidden budget item almost every first-time builder underestimates. Four: soft costs — plans, engineering, permits, and surveys.",
      "## Where people overspend",
      "Complex geometry. Every notch in the rectangle adds cost to roofing, siding, and foundation. Second stories built late in the design process. And changing windows and doors after the building is ordered.",
      "## Where people save smart",
      "A simple rectangular footprint with porches for character. A post-frame shell. Stock plans over custom when a stock plan is 80% right — then spend the difference on modification to close the gap. Use our cost calculator for a rough range, then request a quote tailored to your project.",
    ],
  },
  {
    id: 5,
    slug: "before-you-buy-stock-plan",
    title: "7 Things to Check Before You Buy a Stock Plan",
    excerpt:
      "A stock plan is a smart beginning — if you know what you're buying. Run this checklist before you purchase any set of house plans.",
    category: "Plan Selection",
    author: "Rachel Bottelman",
    image: FLOORPLAN,
    readMinutes: 5,
    publishedAt: new Date("2025-06-10"),
    content: [
      "A good stock plan shortens your timeline by months. A bad purchase decision adds them right back. Here's the checklist our team would run before buying any plan — ours included.",
      "## 1. What's actually included",
      "A buildable set should include floor plans, elevations, an electrical plan, and construction details. Ask exactly what's on the pages before you pay.",
      "## 2. Engineering and stamps",
      "Most stock plans don't include a structural engineering or architectural stamp — ours can be added for a separate cost. Many jurisdictions require one, so know your county's rules first.",
      "## 3. The building system",
      "Can the plan be adapted to steel weld-up, bolt-up, or wood post-frame? Our plans can be modified for any of the three — but not every designer's can.",
      "## 4. The license",
      "You're typically buying the right to build one structure — not to reuse, resell, or transfer the plans. Read the license.",
      "## 5. Your land",
      "Width, depth, setbacks, and the view. A 90-foot-wide plan on a 100-foot-wide lot leaves no room to breathe.",
      "## 6. Your modifications",
      "List the changes you know you'll want. If the list is short, buy the stock plan and a modification quote. If it rewrites the house, start custom.",
      "## 7. The refund policy",
      "Digital plan sets are typically non-refundable once delivered. Make the checklist your friend before checkout, not after.",
    ],
  },
  {
    id: 6,
    slug: "are-barndominiums-energy-efficient",
    title: "Are Barndominiums Energy Efficient?",
    excerpt:
      "Yes — if they're designed properly. How insulation strategy, orientation and window planning make a metal building a comfortable home.",
    category: "Design Tips",
    author: "Joselin Trejo",
    image: "https://images.pexels.com/photos/8134820/pexels-photo-8134820.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=827&w=1400",
    readMinutes: 4,
    publishedAt: new Date("2025-04-08"),
    content: [
      "The honest answer to the efficiency question is the same as with any structure: yes, if it's designed properly. A metal skin is not the deciding factor — the wall assembly and the planning are.",
      "## Insulation strategy matters most",
      "Continuous insulation at the roof and walls, careful sealing at every penetration, and thermal breaks where the structure meets the conditioned space. A post-frame wall, with its deep cavities, can actually outperform a site-built stud wall when detailed well.",
      "## Orientation is free efficiency",
      "Porches on the south and west knock down summer heat gain before it reaches a wall. Window walls face the view — but we size overhangs and glass for your climate zone. These decisions cost nothing at the plan stage and save for decades.",
      "## The airtightness advantage",
      "A well-detailed barndo envelope has fewer seams than most conventional construction. Paired with a right-sized HVAC system and fresh-air strategy, our clients routinely report utility bills well below their previous conventional homes of similar size.",
    ],
  },
];

/* ——————————————————— TESTIMONIALS ——————————————————— */

export const TESTIMONIALS: Testimonial[] = [
  {
    id: 1,
    clientName: "Verified Client",
    location: "Oklahoma",
    quote:
      "The Greg James Design Team is truly first class! Mr. James, Lance and his entire team listen to your thoughts and ideas. They have extremely good communication with their customers and work to bring your dream design to fruition.",
    project: "Custom Barndominium",
    displayOrder: 1,
  },
  {
    id: 2,
    clientName: "The Fleck Family",
    location: "Andersonville, Tennessee",
    quote:
      "From the first sketch, the team understood what Copper Top Estates needed to become. The Loyston is more than a venue — it's the heart of our family's dream, and it came to life exactly as they drew it.",
    project: "The Loyston Wedding Venue",
    displayOrder: 2,
  },
  {
    id: 3,
    clientName: "R. Martinez",
    location: "Central Texas",
    quote:
      "We bought a stock plan and asked for a bigger shop and one more bedroom. The modification process was clear, the quote was fair, and the final set was everything we hoped. Build started six weeks later.",
    project: "Plan Modification — Shop & Home",
    displayOrder: 3,
  },
  {
    id: 4,
    clientName: "S. & K. Whitfield",
    location: "Alberta, Canada",
    quote:
      "Working with the team from Canada was seamless. Communication was constant, drafts arrived on schedule, and our post-frame home is now under construction. We recommend them to everyone who asks.",
    project: "Custom Design — Post-Frame Home",
    displayOrder: 4,
  },
];

/* ——————————————————— TEAM ——————————————————— */

export const TEAM: TeamMember[] = [
  {
    id: 1,
    name: "Greg James",
    role: "Founder & Lead Designer",
    bio: "Greg began his career building handmade boats along the Texas Gulf Coast. In 1997 he discovered his love for design and layout, and has since designed countless residential and commercial projects. With over 35 years in the construction industry, he brings deep knowledge of the home building process to every plan.",
    offClock:
      "A passionate art collector, Greg enjoys the thrill of the hunt — scouring art markets and galleries for unique pieces to enrich his home.",
    email: "greg@gregjamesdesigns.com",
    image: "",
    displayOrder: 1,
  },
  {
    id: 2,
    name: "Joselin Trejo",
    role: "Interior Designer",
    bio: "Joselin is a CIDA-accredited Interior Designer and a graduate of the University of Central Oklahoma, where she earned her Bachelor of Fine Arts in Interior Design. Her approach goes beyond aesthetics — she focuses on the emotional, physical, and social impact of environments, ensuring every space is as empathetic as it is functional.",
    offClock:
      "A lifelong learner, Joselin draws fresh perspectives from her love of art, literature, and history.",
    email: "joselin@gregjamesdesigns.com",
    image: "",
    displayOrder: 2,
  },
  {
    id: 3,
    name: "Rachel Bottelman",
    role: "Project Designer",
    bio: "Rachel is a project designer with over six years of experience in residential and commercial design. She's passionate about creating spaces that feel welcoming, intentional, and uniquely tailored to each client. Known for her collaborative approach and thoughtful communication, Rachel brings calm and trust to every project — from concept to completion.",
    offClock:
      "Rachel designed and built a tiny house with her husband, nestled among the pines on a bluff in Northeast Iowa — their quiet getaway and a personal testament to thoughtful design.",
    email: "rachel.b@gregjamesdesigns.com",
    image: "",
    displayOrder: 3,
  },
  {
    id: 4,
    name: "Haley Breeden",
    role: "Architect & Design Consultant",
    bio: "Haley lends architectural rigor to the studio's design work, consulting on structure, code considerations, and the fine details that make a plan buildable. Her review process keeps every set of drawings honest to the jobsite.",
    offClock:
      "Haley can usually be found sketching details by hand — the old way — before anything touches the computer.",
    email: "designteam@gregjamesdesigns.com",
    image: "",
    displayOrder: 4,
  },
  {
    id: 5,
    name: "Beth Navejas",
    role: "Office Manager & Construction Project Manager",
    bio: "Beth keeps the studio's projects, schedules, and clients moving in the same direction. As office manager and construction project manager, she's the steady hand between your design and your build.",
    offClock:
      "Beth is the first one in and the calendar-keeper for the whole team — no deadline survives without her knowing about it.",
    email: "designteam@gregjamesdesigns.com",
    image: "",
    displayOrder: 5,
  },
];
